### ISSUE TITLE
关于`ui-textfield`的命名

### ISSUE THREAD

**Issue by z-song** [balmjs/ui-vue#1]
`ui-textfield`对应`form`表单中的`<input />`

所以我觉得`ui-textfield`改名为`ui-input`会更合适一些

这样的话：
`<ui-input type='text'></ui-input>`对应 `<input type='text' />`
`<ui-input type='password'></ui-input>`对应 `<input type='password' />`
`<ui-input type='email'></ui-input>`对应 `<input type='email' />`

会更清晰一些

**Comment by elf-mouse** [comment]
ui-textfield是参照[MDL官网](https://getmdl.io/components/index.html)的命名规范；<ui-textfield>默认渲染<input>，如果设置<ui-textfield type="textarea">就会渲染<textarea>，含义都为文本域；一开始我也考虑过用ui-input和ui-textarea，后来觉得可以理解的就跟着官网命名走，包括它里面的布局方式也是google独特的一套，跟我们平常做布局有一定差异，需要稍微理解一下
