### ISSUE TITLE
Select Component Style

### ISSUE THREAD

**Issue by milorojas** [balmjs/ui-vue#2]
Is possible to add some style on the select component to look like this
<img width="304" alt="captura de pantalla 2019-02-17 a la s 21 54 45" src="https://user-images.githubusercontent.com/15176512/52922268-d2ba0880-32fe-11e9-85c3-2ef85983f4b4.png">

Instead of this
<img width="544" alt="captura de pantalla 2019-02-17 a la s 21 48 08" src="https://user-images.githubusercontent.com/15176512/52922223-58898400-32fe-11e9-9f7a-2d4513b06a0b.png">

Thanks in advance

**Comment by elf-mouse** [comment]
Thanks for your suggestion.

`ui-select` functions as a wrapper around the browser's native <select> element. (mobile friendly) You can overwrite `ui-select` css or choose `ui-dropdown` instead for enhanced select.

And I will follow MDC official guidance update it in a future release.

Thanks again :)

**Comment by elf-mouse** [comment]
Thanks for your suggestion.

`ui-select` functions as a wrapper around the browser's native select element. (mobile friendly) You can overwrite `ui-select` css or choose `ui-dropdown` instead for enhanced select.

And I will follow MDC official guidance update it in a future release.

Thanks again :)
